### ISSUE TITLE
0 in AnimatedFlipCounter with custom font gets spaced weirdly

### ISSUE THREAD

**Issue by edeuss** [h65wang/flutter-animated-counter#19] opened 2022-12-20 03:17 UTC
For some reason, the 0 in the AnimatedFlipCounter with a custom font is spaced weirdly, so it gets cut off.

Left: Normal Text Widget
Right: AnimatedFlipCounter

![Screenshot_1082](https://user-images.githubusercontent.com/13773566/208573192-766dc4a7-ce88-4294-aacc-03af18ff8278.png)

**Comment by h65wang** [comment] 2022-12-20 03:27
Does it seem that for this particular font, the number `0` is a little bit wider than other digits?

Maybe try using the `padding` property to give some horizontal padding to each digit, see if that solves the problem for you.

**Comment by edeuss** [comment] 2022-12-20 03:42
@h65wang I checked the font 0 spacing, and it looks to be no spacing issue. I am wondering if maybe this is a flutter issue.

**Comment by h65wang** [comment] 2022-12-20 03:48
what do you mean? If you stack number 8 on top of number 0, can you see if 0 is wider?

Also, did you try using padding. Please close this issue if it's solved.

**Comment by edeuss** [comment] 2022-12-20 03:56
> what do you mean?

I checked with a font editor to check the spacing on the font for the 0 character.

Here is a 8 and a 0 stacked:

![Screenshot_1084](https://user-images.githubusercontent.com/13773566/208579901-28e3a8d7-9e03-4edb-9c47-ad9e06a2b79c.png)

> Also, did you try using padding. 

Yes, but it creates too much spacing between the other numbers.
Example of using one 1px on right padding:

![Screenshot_1085](https://user-images.githubusercontent.com/13773566/208580251-cb3908e4-aaec-499b-8888-f572b6682869.png)

**Comment by h65wang** [comment] 2022-12-20 04:10
I took your screenshot and stacked `0` on other digits:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/41172064/208581705-99987eaf-5829-449b-a9ce-701f8c9f399d.png">

From the stacked image, it's clear that the issue is caused by 0 being wider than other numbers in this particular font. It's not a flutter issue.

**Closed as completed by h65wang** 2022-12-20 04:10 UTC
